### PR TITLE
Update library after upstream changes

### PR DESCRIPTION
**Pull request by Bluenix2**
I went through all changes since the library was last checked for conformity (see [Comparing changes](https://github.com/discord/discord-api-docs/compare/4780bd46d44783e97e399eb80f10aaedc8782339..main)).

It should now be up-to-date for commit 6326e4144ed095c6938ec97e83fa4a58b4f41625, see https://github.com/discord/discord-api-docs/compare/6326e4144ed095c6938ec97e83fa4a58b4f41625..main.

### CODE REVIEW

**Comment by Bluenix2** [comment]
As I feared, the circular reference of MessageInteractionMetadataData is causing issues: https://github.com/Bluenix2/discord-typings/pull/40/files#diff-0971aa858cfd57d88198371737b758a3cb10eb030ab44c95c069aae85bf9b974R326

I will have to think about our alternatives here (will likely have to use `Dict[str, Any]` unfortunately) tomorrow

**Comment by silasary** [comment]
Might be worth just putting it in its own file?

**Comment by Bluenix2** [comment]
The issue was that I accidentally missed the `NotRequired` marker on those fields, making the dependency infinite, which even Pyright complains about.

**Comment by Bluenix2** [comment]
Force-pushed the fix to have a cleaner history - merging (rebasing) this now!

**Pull request merged**
